In [1]:
import tensorflow as tf
tf.__version__

/home/jupyter/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/jupyter/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/jupyter/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/jupyter/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:5

'1.14.0'

*after we import TensorFlow (with import tensorflow as tf ), a specific*
*empty default graph is formed. All the nodes we create are automatically associated*
*with that default graph.*

In [2]:
a = tf.constant(5)
b = tf.constant(2)
c = tf.constant(3)

In [3]:
d = tf.multiply(a, b)
e = tf.add(c, b)
f = tf.subtract(d, e)

In [4]:
sess = tf.Session()
outs = sess.run(f)
sess.close()
print("outs = {}".format(outs))

outs = 5


In [5]:
print(tf.get_default_graph())
g = tf.Graph()
print(g)

##### The with statement
* *The with statement is used to wrap the execution of a block with
methods defined by a context manager—an object that has the spe‐
cial method functions .__enter__() to set up a block of code
and .__exit__() to exit the block.*
* *In layman’s terms, it’s very convenient in many cases to execute
some code that requires “setting up” of some kind (like opening a
file, SQL table, etc.) and then always “tearing it down” at the end,
regardless of whether the code ran well or raised any kind of excep‐
tion. In our case we use with to set up a graph and make sure*

##### Fetches
* *In our initial graph example, we request one specific node (node f ) by passing the
variable it was assigned to as an argument to the sess.run() method. This argument
is called fetches , corresponding to the elements of the graph we wish to com‐
pute.*

In [6]:
with tf.Session() as sess:
    fetches = [a, b, c, d, e, f]
    outs = sess.run(fetches)
print("outs = {}".format(outs))
print(type(outs[0]))

outs = [5, 2, 3, 10, 5, 5]
<class 'numpy.int32'>


### Flowing Tensors
##### Nodes are operations, Edges are tensor objects

##### A note on constuctors
*The tf.operator function could be thought of as a constructor,
but to be more precise, this is actually not a constructor at all, but
rather a factory method that sometimes does quite a bit more than
just creating the operator objects.*

In [7]:
import numpy as np
c = tf.constant([[1,2,3],
                [4,5,6]])
print("Python List input: {}".format(c.get_shape()))
c = tf.constant(np.array([
        [[1,2,3],
        [4,5,6]],
    
        [[1,1,1],
        [2,2,2]]
]))
print("3d NumPy array input: {}".format(c.get_shape()))

Python List input: (2, 3)
3d NumPy array input: (2, 2, 3)


In [8]:
sess = tf.InteractiveSession()
c = tf.lin_space(0.0, 4.0, 5)
print("The content of 'c':\n{}\n".format(c.eval()))
sess.close()

The content of 'c':
[0. 1. 2. 3. 4.]



##### Interactive sessions
*tf.InteractiveSession() allows you to replace the usual tf.Ses
sion() , so that you don’t need a variable holding the session for
running ops. This can be useful in interactive Python environ‐
ments, like when writing IPython notebooks, for instance.*

In [9]:
A = tf.constant([ [1,2,3],
                  [4,5,6] ])
print(A.get_shape())

x = tf.constant([1,0,1])
print(x.get_shape())

(2, 3)
(3,)


In [10]:
x = tf.expand_dims(x, 1)
print(x.get_shape())

b = tf.matmul(A, x)

sess = tf.InteractiveSession()
print('matmul result:\n {}'.format(b.eval()))
sess.close()

(3, 1)
matmul result:
 [[ 4]
 [10]]


In [14]:
init_val = tf.random_normal((1, 5), 0, 1)
var = tf.Variable(init_val, name='var')
print("pre run: \n{}".format(var))

init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    post_var = sess.run(var)
    
print("\npost run: \n{}".format(post_var))

pre run: 
<tf.Variable 'var_2:0' shape=(1, 5) dtype=float32_ref>

post run: 
[[ 0.12906128  0.32190734  0.14476825  0.63647956 -0.03584915]]
